"""conversation sessions and user memories

Revision ID: 25a29bebb464
Revises: 20260703_0001
Create Date: 2026-07-09 21:43:08.194827
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "25a29bebb464"
down_revision: str | None = "20260703_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_memories",
        sa.Column("id", sa.Uuid().with_variant(sa.UUID(), "postgresql"), nullable=False),
        sa.Column("user_id", sa.Uuid().with_variant(sa.UUID(), "postgresql"), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_memories_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_memories")),
    )
    op.add_column(
        "conversations", sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "conversations", sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.execute("UPDATE conversations SET last_message_at = created_at")
    op.alter_column("conversations", "last_message_at", nullable=False)
    op.drop_constraint(op.f("uq_conversations_user_id"), "conversations", type_="unique")
    op.create_index(
        "ix_conversations_user_chat_created",
        "conversations",
        ["user_id", "telegram_chat_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_conversations_user_chat_created", table_name="conversations")
    op.create_unique_constraint(
        op.f("uq_conversations_user_id"),
        "conversations",
        ["user_id", "telegram_chat_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("conversations", "last_message_at")
    op.drop_column("conversations", "closed_at")
    op.drop_table("user_memories")
    # ### end Alembic commands ###
